services:
  webdav:
    build: .
    container_name: webdav
    restart: always
    environment:
      - TZ=UTC
    ports:
      - 443:443
    volumes:
      - ./volume/.secret/:/etc/apache2/.secret/
      - ./volume/data/:/var/www/webdav/data/

